class DataModel {
  late String? userId;
  late String productImage;
  late String productName;
  late double productPrice;
  late int quantity;
  List<String> subImages;

  DataModel({
    this.userId,
    required this.subImages,
    required this.productImage,
    required this.productName,
    required this.productPrice,
    this.quantity = 1,
    required double? rating,
  });


  static List<DataModel> skecher = [
    DataModel(
        productImage: "Assets/skechers/sub/a2.png",
        productName: "Skecher",
        productPrice: 100,
        rating: 5.4,
        subImages: [
          "Assets/skechers/sub/a4.png",
          "Assets/skechers/sub/a1.png",
          "Assets/skechers/sub/a2.png",
          "Assets/skechers/sub/a3.png",
        ]),
    DataModel(
        subImages: [
          "Assets/skechers/sub/b1.png",
          "Assets/skechers/sub/b2.png",
          "Assets/skechers/sub/b3.png",
          "Assets/skechers/sub/b4.png",
        ],
        productImage: "Assets/skechers/sub/b2.png",
        productName: "Skecher",
        productPrice: 120,
        rating: 5.5),
    DataModel(
        subImages: [
          "Assets/skechers/sub/b5.png",
          "Assets/skechers/sub/b6.png",
          "Assets/skechers/sub/b7.png",
          "Assets/skechers/sub/b8.png",
        ],
        productImage: "Assets/skechers/sub/b6.png",
        productName: "Skecher",
        productPrice: 140,
        rating: 5.2),
    DataModel(
        subImages: [
          "Assets/skechers/sub/b9.png",
          "Assets/skechers/sub/b10.png",
          "Assets/skechers/sub/b11.png",
          "Assets/skechers/sub/b12.png",
        ],
        productImage: "Assets/skechers/sub/b10.png",
        productName: "Skecher",
        productPrice: 160,
        rating: 5.8),
    DataModel(
        subImages: [
          "Assets/skechers/sub/c1.png",
          "Assets/skechers/sub/c2.png",
          "Assets/skechers/sub/c3.png",
          "Assets/skechers/sub/c4.png",
        ],
        productImage: "Assets/skechers/sub/c4.png",
        productName: "Skecher",
        productPrice: 180,
        rating: 3.2),
    DataModel(
        subImages: [
          "Assets/skechers/sub/d1.png",
          "Assets/skechers/sub/d2.png",
          "Assets/skechers/sub/d3.png",
          "Assets/skechers/sub/d4.png",
        ],
        productImage: "Assets/skechers/sub/d4.png",
        productName: "Skecher",
        productPrice: 200,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/skechers/sub/d9.png",
          "Assets/skechers/sub/d10.png",
          "Assets/skechers/sub/d11.png",
          "Assets/skechers/sub/d12.png",
        ],
        productImage: "Assets/skechers/sub/d10.png",
        productName: "Skecher",
        productPrice: 220,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/skechers/sub/d5.png",
          "Assets/skechers/sub/d6.png",
          "Assets/skechers/sub/d7.png",
          "Assets/skechers/sub/d8.png",
        ],
        productImage: "Assets/skechers/sub/d6.png",
        productName: "Skecher",
        productPrice: 140,
        rating: 3.5),
    DataModel(
        subImages: [
          "Assets/skechers/sub/e1.png",
          "Assets/skechers/sub/e2.png",
          "Assets/skechers/sub/e3.png",
          "Assets/skechers/sub/e4.png",
        ],
        productImage: "Assets/skechers/sub/e2.png",
        productName: "Skecher",
        productPrice: 240,
        rating: 5.1),
    DataModel(
        subImages: [
          "Assets/skechers/sub/f5.png",
          "Assets/skechers/sub/f6.png",
          "Assets/skechers/sub/f7.png",
          "Assets/skechers/sub/f8.png",
        ],
        productImage: "Assets/skechers/sub/f6.png",
        productName: "Skecher",
        productPrice: 260,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/skechers/sub/f1.png",
          "Assets/skechers/sub/f2.png",
          "Assets/skechers/sub/f3.png",
          "Assets/skechers/sub/f4.png",
        ],
        productImage: "Assets/skechers/sub/f2.png",
        productName: "Skecher",
        productPrice: 260,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/skechers/sub/h1.png",
          "Assets/skechers/sub/h2.png",
          "Assets/skechers/sub/h3.png",
          "Assets/skechers/sub/h4.png",
        ],
        productImage: "Assets/skechers/sub/h3.png",
        productName: "Skecher",
        productPrice: 280,
        rating: 5.3),
    DataModel(
        subImages: [
          "Assets/skechers/sub/n1.png",
          "Assets/skechers/sub/n2.png",
          "Assets/skechers/sub/n3.png",
          "Assets/skechers/sub/n4.png",
        ],
        productImage: "Assets/skechers/sub/n2.png",
        productName: "Skecher",
        productPrice: 300,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/skechers/sub/s1.png",
          "Assets/skechers/sub/s2.png",
          "Assets/skechers/sub/s3.png",
          "Assets/skechers/sub/s4.png",
        ],
        productImage: "Assets/skechers/sub/s3.png",
        productName: "Skecher",
        productPrice: 140,
        rating: 4.4),
    DataModel(
        subImages: [
          "Assets/skechers/sub/sc1.png",
          "Assets/skechers/sub/sc2.png",
          "Assets/skechers/sub/sc3.png",
          "Assets/skechers/sub/sc4.png",
        ],
        productImage: "Assets/skechers/sub/sc3.png",
        productName: "Skecher",
        productPrice: 320,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/skechers/sub/st1.png",
          "Assets/skechers/sub/st2.png",
          "Assets/skechers/sub/st3.png",
          "Assets/skechers/sub/st4.png",
        ],
        productImage: "Assets/skechers/sub/st2.png",
        productName: "Skecher",
        productPrice: 340,
        rating: 3.6),
    DataModel(
        subImages: [
          "Assets/skechers/sub/su.png",
          "Assets/skechers/sub/su2.png",
          "Assets/skechers/sub/su3.png",
          "Assets/skechers/sub/su4.png",
        ],
        productImage: "Assets/skechers/sub/su2.png",
        productName: "Skecher",
        productPrice: 360,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/skechers/sub/sub1.png",
          "Assets/skechers/sub/sub2.png",
          "Assets/skechers/sub/sub3.png",
          "Assets/skechers/sub/sub4.png",
        ],
        productImage: "Assets/skechers/sub/sub2.png",
        productName: "Skecher",
        productPrice: 140,
        rating: 3.3),
    DataModel(
        subImages: [
          "Assets/skechers/sub/sub5.png",
          "Assets/skechers/sub/sub6.png",
          "Assets/skechers/sub/sub7.png",
          "Assets/skechers/sub/sub8.png",
        ],
        productImage: "Assets/skechers/sub/sub2.png",
        productName: "Skecher",
        productPrice: 380,
        rating: 3.1),

    DataModel(
        subImages: [
          "Assets/skechers/sub/y1.png",
          "Assets/skechers/sub/y2.png",
          "Assets/skechers/sub/y3.png",
          "Assets/skechers/sub/y4.png",
        ],
        productImage: "Assets/skechers/sub/y2.png",
        productName: "Skecher",
        productPrice: 140,
        rating: 4.2),
    DataModel(
        subImages: [
          "Assets/skechers/sub/p1.png",
          "Assets/skechers/sub/p2.png",
          "Assets/skechers/sub/p3.png",
          "Assets/skechers/sub/p4.png",
        ],
        productImage: "Assets/skechers/sub/p1.png",
        productName: "Skecher",
        productPrice: 220,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/skechers/sub/z1.png",
          "Assets/skechers/sub/z2.png",
          "Assets/skechers/sub/z3.png",
          "Assets/skechers/sub/z4.png",
        ],
        productImage: "Assets/skechers/sub/z2.png",
        productName: "Skecher",
        productPrice: 240,
        rating: 5.0),
  ];
  static List<DataModel> puma = [
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/a1.png",
          "Assets/pumabrand/pum/a2.png",
          "Assets/pumabrand/pum/a3.png",
          "Assets/pumabrand/pum/a4.png",
        ],
        productImage: "Assets/pumabrand/pum/a2.png",
        productName: "Puma",
        productPrice: 100,
        rating: 5.4),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/a5.png",
          "Assets/pumabrand/pum/a6.png",
          "Assets/pumabrand/pum/a7.png",
          "Assets/pumabrand/pum/a8.png",
        ],
        productImage: "Assets/pumabrand/pum/a6.png",
        productName: "Puma",
        productPrice: 118,
        rating: 4.4),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/b1.png",
          "Assets/pumabrand/pum/b2.png",
          "Assets/pumabrand/pum/b3.png",
          "Assets/pumabrand/pum/b4.png",
        ],
        productImage: "Assets/pumabrand/pum/b4.png",
        productName: "Puma",
        productPrice: 136,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/b5.png",
          "Assets/pumabrand/pum/b6.png",
          "Assets/pumabrand/pum/b7.png",
          "Assets/pumabrand/pum/b8.png",
        ],
        productImage: "Assets/pumabrand/pum/b6.png",
        productName: "Puma",
        productPrice: 154,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/c5.png",
          "Assets/pumabrand/pum/c6.png",
          "Assets/pumabrand/pum/c7.png",
          "Assets/pumabrand/pum/c8.png",
        ],
        productImage: "Assets/pumabrand/pum/c8.png",
        productName: "Puma",
        productPrice: 244,
        rating: 3.5),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/c1.png",
          "Assets/pumabrand/pum/c2.png",
          "Assets/pumabrand/pum/c3.png",
          "Assets/pumabrand/pum/c4.png",
        ],
        productImage: "Assets/pumabrand/pum/c4.png",
        productName: "Puma",
        productPrice: 172,
        rating: 3.7),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/d1.png",
          "Assets/pumabrand/pum/d2.png",
          "Assets/pumabrand/pum/d3.png",
          "Assets/pumabrand/pum/d4.png",
        ],
        productImage: "Assets/pumabrand/pum/d4.png",
        productName: "Puma",
        productPrice: 190,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/d5.png",
          "Assets/pumabrand/pum/d6.png",
          "Assets/pumabrand/pum/d7.png",
          "Assets/pumabrand/pum/d8.png",
        ],
        productImage: "Assets/pumabrand/pum/d7.png",
        productName: "Puma",
        productPrice: 208,
        rating: 3.6),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/e5.png",
          "Assets/pumabrand/pum/e6.png",
          "Assets/pumabrand/pum/e7.png",
          "Assets/pumabrand/pum/e8.png",
        ],
        productImage: "Assets/pumabrand/pum/e6.png",
        productName: "Puma",
        productPrice: 226,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/e1.png",
          "Assets/pumabrand/pum/e2.png",
          "Assets/pumabrand/pum/e3.png",
          "Assets/pumabrand/pum/e4.png",
        ],
        productImage: "Assets/pumabrand/pum/e4.png",
        productName: "Puma",
        productPrice: 244,
        rating: 4.3),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/f1.png",
          "Assets/pumabrand/pum/f2.png",
          "Assets/pumabrand/pum/f3.png",
          "Assets/pumabrand/pum/f4.png",
        ],
        productImage: "Assets/pumabrand/pum/f4.png",
        productName: "Puma",
        productPrice: 244,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/f5.png",
          "Assets/pumabrand/pum/f6.png",
          "Assets/pumabrand/pum/f7.png",
          "Assets/pumabrand/pum/f8.png",
        ],
        productImage: "Assets/pumabrand/pum/f6.png",
        productName: "Puma",
        productPrice: 262,
        rating: 5.8),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/g5.png",
          "Assets/pumabrand/pum/g6.png",
          "Assets/pumabrand/pum/g7.png",
          "Assets/pumabrand/pum/g8.png",
        ],
        productImage: "Assets/pumabrand/pum/g8.png",
        productName: "Puma",
        productPrice: 280,
        rating: 5.0),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/g1.png",
          "Assets/pumabrand/pum/g2.png",
          "Assets/pumabrand/pum/g3.png",
          "Assets/pumabrand/pum/g4.png",
        ],
        productImage: "Assets/pumabrand/pum/g4.png",
        productName: "Puma",
        productPrice: 298,
        rating: 5.7),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/h1.png",
          "Assets/pumabrand/pum/h2.png",
          "Assets/pumabrand/pum/h3.png",
          "Assets/pumabrand/pum/h4.png",
        ],
        productImage: "Assets/pumabrand/pum/h4.png",
        productName: "Puma",
        productPrice: 244,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/h5.png",
          "Assets/pumabrand/pum/h6.png",
          "Assets/pumabrand/pum/h7.png",
          "Assets/pumabrand/pum/h8.png",
        ],
        productImage: "Assets/pumabrand/pum/h8.png",
        productName: "Puma",
        productPrice: 316,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/k5.png",

          "Assets/pumabrand/pum/k7.png",
          "Assets/pumabrand/pum/k8.png",
        ],
        productImage: "Assets/pumabrand/pum/k5.png",
        productName: "Puma",
        productPrice: 334,
        rating: 3.2),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/k1.png",
          "Assets/pumabrand/pum/k2.png",
          "Assets/pumabrand/pum/k3.png",
          "Assets/pumabrand/pum/k4.png",
        ],
        productImage: "Assets/pumabrand/pum/k4.png",
        productName: "Puma",
        productPrice: 244,
        rating: 3.3),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/t1.png",
          "Assets/pumabrand/pum/t2.png",
          "Assets/pumabrand/pum/t3.png",
          "Assets/pumabrand/pum/t4.png",
        ],
        productImage: "Assets/pumabrand/pum/t4.png",
        productName: "Puma",
        productPrice: 352,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/t5.png",
          "Assets/pumabrand/pum/t6.png",
          "Assets/pumabrand/pum/t7.png",
          "Assets/pumabrand/pum/t8.png",
        ],
        productImage: "Assets/pumabrand/pum/t8.png",
        productName: "Puma",
        productPrice: 370,
        rating: 5.1),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/z5.png",
          "Assets/pumabrand/pum/z6.png",
          "Assets/pumabrand/pum/z7.png",
          "Assets/pumabrand/pum/z8.png",
        ],
        productImage: "Assets/pumabrand/pum/z8.png",
        productName: "Puma",
        productPrice: 388,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/z1.png",
          "Assets/pumabrand/pum/z2.png",
          "Assets/pumabrand/pum/z3.png",
          "Assets/pumabrand/pum/z4.png",
        ],
        productImage: "Assets/pumabrand/pum/z4.png",
        productName: "Puma",
        productPrice: 406,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/v1.png",
          "Assets/pumabrand/pum/v2.png",
          "Assets/pumabrand/pum/v3.png",
          "Assets/pumabrand/pum/v4.png",
        ],
        productImage: "Assets/pumabrand/pum/v4.png",
        productName: "Puma",
        productPrice: 424,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/pumabrand/pum/v5.png",
          "Assets/pumabrand/pum/v6.png",
          "Assets/pumabrand/pum/v7.png",
          "Assets/pumabrand/pum/v8.png",
        ],
        productImage: "Assets/pumabrand/pum/v8.png",
        productName: "Puma",
        productPrice: 442,
        rating: 3.5),
  ];
  static List<DataModel> adidas = [
    DataModel(
        subImages: [
          "Assets/Adidas/add/a1.png",
          "Assets/Adidas/add/a3.png",
          "Assets/Adidas/add/a4.png",
          "Assets/Adidas/add/a2.png",
        ],
        productImage: "Assets/Adidas/add/a3.png",
        productName: "Adidas",
        productPrice: 137,
        rating: 5.4),
    DataModel(
        subImages: [
          "Assets/Adidas/add/b1.png",
          "Assets/Adidas/add/b3.png",
          "Assets/Adidas/add/b4.png",
          "Assets/Adidas/add/b2.png",
        ],
        productImage: "Assets/Adidas/add/b2.png",
        productName: "Adidas",
        productPrice: 207,
        rating: 3.7),
    DataModel(
        subImages: [
          "Assets/Adidas/add/c1.png",
          "Assets/Adidas/add/c.png",
          "Assets/Adidas/add/c4.png",
          "Assets/Adidas/add/c2.png",
        ],
        productImage: "Assets/Adidas/add/c4.png",
        productName: "Adidas",
        productPrice: 190,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/Adidas/add/d1.png",
          "Assets/Adidas/add/d3.png",
          "Assets/Adidas/add/d4.png",
          "Assets/Adidas/add/d2.png",
        ],
        productImage: "Assets/Adidas/add/d4.png",
        productName: "Adidas",
        productPrice: 140,
        rating: 4.2),
    DataModel(
        subImages: [
          "Assets/Adidas/add/e1.png",
          "Assets/Adidas/add/e3.png",
          "Assets/Adidas/add/e4.png",
          "Assets/Adidas/add/e2.png",
        ],
        productImage: "Assets/Adidas/add/e3.png",
        productName: "Adidas",
        productPrice: 140,
        rating: 5.0),
    DataModel(
        subImages: [
          "Assets/Adidas/add/g1.png",
          "Assets/Adidas/add/g3.png",
          "Assets/Adidas/add/g4.png",
          "Assets/Adidas/add/g2.png",
        ],
        productImage: "Assets/Adidas/add/g2.png",
        productName: "Adidas",
        productPrice: 144,
        rating: 5.1),
    DataModel(
        subImages: [
          "Assets/Adidas/add/g1.png",
          "Assets/Adidas/add/g3.png",
          "Assets/Adidas/add/g4.png",
          "Assets/Adidas/add/g2.png",
        ],
        productImage: "Assets/Adidas/add/g2.png",
        productName: "Adidas",
        productPrice: 151,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/Adidas/add/h1.png",
          "Assets/Adidas/add/h3.png",
          "Assets/Adidas/add/h4.png",
          "Assets/Adidas/add/h2.png",
        ],
        productImage: "Assets/Adidas/add/h4.png",
        productName: "Adidas",
        productPrice: 158,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/Adidas/add/j1.png",
          "Assets/Adidas/add/j3.png",
          "Assets/Adidas/add/j4.png",
          "Assets/Adidas/add/j2.png",
        ],
        productImage: "Assets/Adidas/add/j4.png",
        productName: "Adidas",
        productPrice: 165,
        rating: 4.3),
    DataModel(
        subImages: [
          "Assets/Adidas/add/k1.png",
          "Assets/Adidas/add/k3.png",
          "Assets/Adidas/add/k4.png",
          "Assets/Adidas/add/k2.png",
        ],
        productImage: "Assets/Adidas/add/k3.png",
        productName: "Adidas",
        productPrice: 172,
        rating: 6.0),
    DataModel(
        subImages: [
          "Assets/Adidas/add/p1.png",
          "Assets/Adidas/add/p3.png",
          "Assets/Adidas/add/p4.png",
          "Assets/Adidas/add/p2.png",
        ],
        productImage: "Assets/Adidas/add/p3.png",
        productName: "Adidas",
        productPrice: 179,
        rating: 3.6),
    DataModel(
        subImages: [
          "Assets/Adidas/add/t1.png",
          "Assets/Adidas/add/t3.png",
          "Assets/Adidas/add/t4.png",
          "Assets/Adidas/add/t2.png",
        ],
        productImage: "Assets/Adidas/add/t3.png",
        productName: "Adidas",
        productPrice: 186,
        rating: 5.5),
    DataModel(
        subImages: [
          "Assets/Adidas/add/z1.png",
          "Assets/Adidas/add/z3.png",
          "Assets/Adidas/add/z4.png",
          "Assets/Adidas/add/z2.png",
        ],
        productImage: "Assets/Adidas/add/z3.png",
        productName: "Adidas",
        productPrice: 193,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/Adidas/add/z5.png",
          "Assets/Adidas/add/z6.png",
          "Assets/Adidas/add/z7.png",
          "Assets/Adidas/add/z8.png",
        ],
        productImage: "Assets/Adidas/add/z7.png",
        productName: "Adidas",
        productPrice: 200,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/Adidas/add/t5.png",
          "Assets/Adidas/add/t6.png",
          "Assets/Adidas/add/t7.png",
          "Assets/Adidas/add/t8.png",
        ],
        productImage: "Assets/Adidas/add/t7.png",
        productName: "Adidas",
        productPrice: 207,
        rating: 3.2),
    DataModel(
        subImages: [
          "Assets/Adidas/add/p5.png",
          "Assets/Adidas/add/p6.png",
          "Assets/Adidas/add/p7.png",
          "Assets/Adidas/add/p8.png",
        ],
        productImage: "Assets/Adidas/add/p7.png",
        productName: "Adidas",
        productPrice: 214,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/Adidas/add/k5.png",
          "Assets/Adidas/add/k6.png",
          "Assets/Adidas/add/k7.png",
          "Assets/Adidas/add/k8.png",
        ],
        productImage: "Assets/Adidas/add/k7.png",
        productName: "Adidas",
        productPrice: 221,
        rating: 4.4),
    DataModel(
        subImages: [
          "Assets/Adidas/add/j5.png",
          "Assets/Adidas/add/j6.png",
          "Assets/Adidas/add/j7.png",
          "Assets/Adidas/add/j8.png",
        ],
        productImage: "Assets/Adidas/add/j7.png",
        productName: "Adidas",
        productPrice: 228,
        rating: 3.9),
    DataModel(
        subImages: [
          "Assets/Adidas/add/h5.png",
          "Assets/Adidas/add/h6.png",
          "Assets/Adidas/add/h7.png",
          "Assets/Adidas/add/h8.png",
        ],
        productImage: "Assets/Adidas/add/h7.png",
        productName: "Adidas",
        productPrice: 235,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/Adidas/add/g5.png",
          "Assets/Adidas/add/g6.png",
          "Assets/Adidas/add/g7.png",
          "Assets/Adidas/add/g8.png",
        ],
        productImage: "Assets/Adidas/add/g7.png",
        productName: "Adidas",
        productPrice: 242,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/Adidas/add/e5.png",
          "Assets/Adidas/add/e6.png",
          "Assets/Adidas/add/e7.png",
          "Assets/Adidas/add/e8.png",
        ],
        productImage: "Assets/Adidas/add/e7.png",
        productName: "Adidas",
        productPrice: 249,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/Adidas/add/d5.png",
          "Assets/Adidas/add/d6.png",
          "Assets/Adidas/add/d7.png",
          "Assets/Adidas/add/d8.png",
        ],
        productImage: "Assets/Adidas/add/d7.png",
        productName: "Adidas",
        productPrice: 256,
        rating: 4.5),
    DataModel(
        subImages: [
          "Assets/Adidas/add/b5.png",
          "Assets/Adidas/add/b6.png",
          "Assets/Adidas/add/b7.png",
          "Assets/Adidas/add/b8.png",
        ],
        productImage: "Assets/Adidas/add/b6.png",
        productName: "Adidas",
        productPrice: 263,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/Adidas/add/a5.png",
          "Assets/Adidas/add/a6.png",
          "Assets/Adidas/add/a7.png",
          "Assets/Adidas/add/a8.png",
        ],
        productImage: "Assets/Adidas/add/a6.png",
        productName: "Adidas",
        productPrice: 270,
        rating: 4.0),
  ];
  static List<DataModel> nike = [
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/a1.png",
          "Assets/nikebrand/nike/a3.png",
          "Assets/nikebrand/nike/a4.png",
          "Assets/nikebrand/nike/a5.png",
        ],
        productImage: "Assets/nikebrand/nike/a3.png",
        productName: "Nike",
        productPrice: 139,
        rating: 3.5),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/b1.png",
          "Assets/nikebrand/nike/b3.png",
          "Assets/nikebrand/nike/b4.png",
          "Assets/nikebrand/nike/b5.png",
        ],
        productImage: "Assets/nikebrand/nike/b3.png",
        productName: "Nike",
        productPrice: 120,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/c1.png",
          "Assets/nikebrand/nike/c3.png",
          "Assets/nikebrand/nike/c4.png",
          "Assets/nikebrand/nike/c5.png",
        ],
        productImage: "Assets/nikebrand/nike/c3.png",
        productName: "Nike",
        productPrice: 166,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/d1.png",
          "Assets/nikebrand/nike/d3.png",
          "Assets/nikebrand/nike/d4.png",
          "Assets/nikebrand/nike/d5.png",
        ],
        productImage: "Assets/nikebrand/nike/d1.png",
        productName: "Nike",
        productPrice: 180,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/e1.png",
          "Assets/nikebrand/nike/e3.png",
          "Assets/nikebrand/nike/e4.png",
          "Assets/nikebrand/nike/e5.png",
        ],
        productImage: "Assets/nikebrand/nike/e3.png",
        productName: "Nike",
        productPrice: 160,
        rating: 3.6),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/f1.png",
          "Assets/nikebrand/nike/f3.png",
          "Assets/nikebrand/nike/f4.png",
          "Assets/nikebrand/nike/f5.png",
        ],
        productImage: "Assets/nikebrand/nike/f3.png",
        productName: "Nike",
        productPrice: 175,
        rating: 5.4),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/g1.png",
          "Assets/nikebrand/nike/g3.png",
          "Assets/nikebrand/nike/g4.png",
          "Assets/nikebrand/nike/g5.png",
        ],
        productImage: "Assets/nikebrand/nike/g3.png",
        productName: "Nike",
        productPrice: 190,
        rating: 4.5),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/h1.png",
          "Assets/nikebrand/nike/h3.png",
          "Assets/nikebrand/nike/h4.png",
          "Assets/nikebrand/nike/h5.png",
        ],
        productImage: "Assets/nikebrand/nike/h3.png",
        productName: "Nike",
        productPrice: 205,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/k1.png",
          "Assets/nikebrand/nike/k3.png",
          "Assets/nikebrand/nike/k4.png",
          "Assets/nikebrand/nike/k5.png",
        ],
        productImage: "Assets/nikebrand/nike/k3.png",
        productName: "Nike",
        productPrice: 220,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/p1.png",
          "Assets/nikebrand/nike/p3.png",
          "Assets/nikebrand/nike/p4.png",
          "Assets/nikebrand/nike/p5.png",
        ],
        productImage: "Assets/nikebrand/nike/p3.png",
        productName: "Nike",
        productPrice: 235,
        rating: 4.3),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/z1.png",
          "Assets/nikebrand/nike/z3.png",
          "Assets/nikebrand/nike/z4.png",
          "Assets/nikebrand/nike/z5.png",
        ],
        productImage: "Assets/nikebrand/nike/z3.png",
        productName: "Nike",
        productPrice: 250,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/z5.png",
          "Assets/nikebrand/nike/z6.png",
          "Assets/nikebrand/nike/z7.png",
          "Assets/nikebrand/nike/z8.png",
        ],
        productImage: "Assets/nikebrand/nike/z7.png",
        productName: "Nike",
        productPrice: 265,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/p5.png",
          "Assets/nikebrand/nike/p6.png",
          "Assets/nikebrand/nike/p7.png",
          "Assets/nikebrand/nike/p8.png",
        ],
        productImage: "Assets/nikebrand/nike/p7.png",
        productName: "Nike",
        productPrice: 280,
        rating: 5.0),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/k5.png",
          "Assets/nikebrand/nike/k6.png",
          "Assets/nikebrand/nike/k7.png",
          "Assets/nikebrand/nike/k8.png",
        ],
        productImage: "Assets/nikebrand/nike/k6.png",
        productName: "Nike",
        productPrice: 295,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/g5.png",
          "Assets/nikebrand/nike/g6.png",
          "Assets/nikebrand/nike/g7.png",
          "Assets/nikebrand/nike/g8.png",
        ],
        productImage: "Assets/nikebrand/nike/g6.png",
        productName: "Nike",
        productPrice: 310,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/h5.png",
          "Assets/nikebrand/nike/h6.png",
          "Assets/nikebrand/nike/h7.png",
          "Assets/nikebrand/nike/h8.png",
        ],
        productImage: "Assets/nikebrand/nike/h6.png",
        productName: "Nike",
        productPrice: 325,
        rating: 3.3),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/e5.png",
          "Assets/nikebrand/nike/e6.png",
          "Assets/nikebrand/nike/e7.png",
          "Assets/nikebrand/nike/e8.png",
        ],
        productImage: "Assets/nikebrand/nike/e6.png",
        productName: "Nike",
        productPrice: 340,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/f5.png",
          "Assets/nikebrand/nike/f6.png",
          "Assets/nikebrand/nike/f7.png",
          "Assets/nikebrand/nike/f8.png",
        ],
        productImage: "Assets/nikebrand/nike/f5.png",
        productName: "Nike",
        productPrice: 355,
        rating: 5.5),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/d5.png",
          "Assets/nikebrand/nike/d6.png",
          "Assets/nikebrand/nike/d7.png",
          "Assets/nikebrand/nike/d8.png",
        ],
        productImage: "Assets/nikebrand/nike/d6.png",
        productName: "Nike",
        productPrice: 370,
        rating: 5.3),
    DataModel(
        subImages: [
          "Assets/nikebrand/nike/c5.png",
          "Assets/nikebrand/nike/c6.png",
          "Assets/nikebrand/nike/c7.png",
          "Assets/nikebrand/nike/c8.png",
        ],
        productImage: "Assets/nikebrand/nike/c6.png",
        productName: "Nike",
        productPrice: 385,
        rating: 4.2),

  ];
  static List<DataModel> rebok = [
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/a1.png",
          "Assets/rebookbrand/reb/a2.png",
          "Assets/rebookbrand/reb/a3.png",
          "Assets/rebookbrand/reb/a4.png",
        ],
        productImage: "Assets/rebookbrand/reb/a4.png",
        productName: "Rebok",
        productPrice: 130,
        rating: 5.7),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/c1.png",
          "Assets/rebookbrand/reb/c2.png",
          "Assets/rebookbrand/reb/c3.png",
          "Assets/rebookbrand/reb/c4.png",
        ],
        productImage: "Assets/rebookbrand/reb/c1.png",
        productName: "Rebok",
        productPrice: 141,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/d1.png",
          "Assets/rebookbrand/reb/d2.png",
          "Assets/rebookbrand/reb/d3.png",
          "Assets/rebookbrand/reb/d4.png",
        ],
        productImage: "Assets/rebookbrand/reb/d3.png",
        productName: "Rebok",
        productPrice: 152,
        rating: 3.9),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/e1.png",
          "Assets/rebookbrand/reb/e2.png",
          "Assets/rebookbrand/reb/e3.png",
          "Assets/rebookbrand/reb/e4.png",
        ],
        productImage: "Assets/rebookbrand/reb/e2.png",
        productName: "Rebok",
        productPrice: 163,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/f1.png",
          "Assets/rebookbrand/reb/f2.png",
          "Assets/rebookbrand/reb/f3.png",
          "Assets/rebookbrand/reb/f4.png",
        ],
        productImage: "Assets/rebookbrand/reb/f2.png",
        productName: "Rebok",
        productPrice: 174,
        rating: 6.0),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/h1.png",
          "Assets/rebookbrand/reb/h2.png",
          "Assets/rebookbrand/reb/h3.png",
          "Assets/rebookbrand/reb/h4.png",
        ],
        productImage: "Assets/rebookbrand/reb/h2.png",
        productName: "Rebok",
        productPrice: 185,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/k1.png",
          "Assets/rebookbrand/reb/k2.png",
          "Assets/rebookbrand/reb/k3.png",
          "Assets/rebookbrand/reb/k4.png",
        ],
        productImage: "Assets/rebookbrand/reb/k2.png",
        productName: "Rebok",
        productPrice: 130,
        rating: 5.5),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/s1.png",
          "Assets/rebookbrand/reb/s2.png",
          "Assets/rebookbrand/reb/s3.png",
          "Assets/rebookbrand/reb/s4.png",
        ],
        productImage: "Assets/rebookbrand/reb/s2.png",
        productName: "Rebok",
        productPrice: 196,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/z1.png",
          "Assets/rebookbrand/reb/z2.png",
          "Assets/rebookbrand/reb/z3.png",
          "Assets/rebookbrand/reb/z4.png",
        ],
        productImage: "Assets/rebookbrand/reb/z3.png",
        productName: "Rebok",
        productPrice: 207,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/c5.png",
          "Assets/rebookbrand/reb/c6.png",
          "Assets/rebookbrand/reb/c7.png",
          "Assets/rebookbrand/reb/c8.png",
        ],
        productImage: "Assets/rebookbrand/reb/c7.png",
        productName: "Rebok",
        productPrice: 218,
        rating: 5.4),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/b5.png",
          "Assets/rebookbrand/reb/b6.png",
          "Assets/rebookbrand/reb/b7.png",
          "Assets/rebookbrand/reb/b8.png",
        ],
        productImage: "Assets/rebookbrand/reb/b7.png",
        productName: "Rebok",
        productPrice: 130,
        rating: 3.2),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/a5.png",
          "Assets/rebookbrand/reb/a6.png",
          "Assets/rebookbrand/reb/a7.png",
          "Assets/rebookbrand/reb/a8.png",
        ],
        productImage: "Assets/rebookbrand/reb/a6.png",
        productName: "Rebok",
        productPrice: 229,
        rating: 5.1),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/d5.png",
          "Assets/rebookbrand/reb/d6.png",
          "Assets/rebookbrand/reb/d7.png",
          "Assets/rebookbrand/reb/d8.png",
        ],
        productImage: "Assets/rebookbrand/reb/d7.png",
        productName: "Rebok",
        productPrice: 240,
        rating: 5.8),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/e5.png",
          "Assets/rebookbrand/reb/e6.png",
          "Assets/rebookbrand/reb/e7.png",
          "Assets/rebookbrand/reb/e8.png",
        ],
        productImage: "Assets/rebookbrand/reb/e7.png",
        productName: "Rebok",
        productPrice: 251,
        rating: 3.5),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/f5.png",
          "Assets/rebookbrand/reb/f6.png",
          "Assets/rebookbrand/reb/f7.png",
          "Assets/rebookbrand/reb/f8.png",
        ],
        productImage: "Assets/rebookbrand/reb/f7.png",
        productName: "Rebok",
        productPrice: 262,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/f5.png",
          "Assets/rebookbrand/reb/f6.png",
          "Assets/rebookbrand/reb/f7.png",
          "Assets/rebookbrand/reb/f8.png",
        ],
        productImage: "Assets/rebookbrand/reb/f7.png",
        productName: "Rebok",
        productPrice: 130,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/c5.png",
          "Assets/rebookbrand/reb/c6.png",
          "Assets/rebookbrand/reb/c7.png",
          "Assets/rebookbrand/reb/c8.png",
        ],
        productImage: "Assets/rebookbrand/reb/c6.png",
        productName: "Rebok",
        productPrice: 273,
        rating: 3.0),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/s5.png",
          "Assets/rebookbrand/reb/s6.png",
          "Assets/rebookbrand/reb/s7.png",
          "Assets/rebookbrand/reb/s8.png",
        ],
        productImage: "Assets/rebookbrand/reb/s7.png",
        productName: "Rebok",
        productPrice: 284,
        rating: 4.4),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/z5.png",
          "Assets/rebookbrand/reb/z6.png",
          "Assets/rebookbrand/reb/z7.png",
          "Assets/rebookbrand/reb/z8.png",
        ],
        productImage: "Assets/rebookbrand/reb/z7.png",
        productName: "Rebok",
        productPrice: 295,
        rating: 5.2),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/l1.png",
          "Assets/rebookbrand/reb/l2.png",
          "Assets/rebookbrand/reb/l3.png",
          "Assets/rebookbrand/reb/l4.png",
        ],
        productImage: "Assets/rebookbrand/reb/l3.png",
        productName: "Rebok",
        productPrice: 130,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/l5.png",
          "Assets/rebookbrand/reb/l6.png",
          "Assets/rebookbrand/reb/l7.png",
          "Assets/rebookbrand/reb/l8.png",
        ],
        productImage: "Assets/rebookbrand/reb/l6.png",
        productName: "Rebok",
        productPrice: 306,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/j1.png",
          "Assets/rebookbrand/reb/j2.png",
          "Assets/rebookbrand/reb/j3.png",
          "Assets/rebookbrand/reb/j5.png",
        ],
        productImage: "Assets/rebookbrand/reb/j3.png",
        productName: "Rebok",
        productPrice: 317,
        rating: 4.2),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/j6.png",
          "Assets/rebookbrand/reb/j7.png",
          "Assets/rebookbrand/reb/j8.png",
        ],
        productImage: "Assets/rebookbrand/reb/j7.png",
        productName: "Rebok",
        productPrice: 328,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/rebookbrand/reb/g1.png",
          "Assets/rebookbrand/reb/g2.png",
          "Assets/rebookbrand/reb/g3.png",
          "Assets/rebookbrand/reb/g4.png",
        ],
        productImage: "Assets/rebookbrand/reb/g2.png",
        productName: "Rebok",
        productPrice: 339,
        rating: 4.7),
  ];

  static List<DataModel> newbalance = [
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/a1.png",
          "Assets/newbalancebrand/new/a2.png",
          "Assets/newbalancebrand/new/a3.png",
          "Assets/newbalancebrand/new/a4.png",
        ],
        productImage: "Assets/newbalancebrand/new/a2.png",
        productName: "Newbal",
        productPrice: 197,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/b1.png",
          "Assets/newbalancebrand/new/b2.png",
          "Assets/newbalancebrand/new/b3.png",
          "Assets/newbalancebrand/new/b4.png",
        ],
        productImage: "Assets/newbalancebrand/new/b2.png",
        productName: "Newbal",
        productPrice: 206,
        rating: 5.3),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/c1.png",
          "Assets/newbalancebrand/new/c2.png",
          "Assets/newbalancebrand/new/c3.png",
          "Assets/newbalancebrand/new/c4.png",
        ],
        productImage: "Assets/newbalancebrand/new/c3.png",
        productName: "Newbal",
        productPrice: 215,
        rating: 4.5),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/d1.png",
          "Assets/newbalancebrand/new/d2.png",
          "Assets/newbalancebrand/new/d3.png",
          "Assets/newbalancebrand/new/d4.png",
        ],
        productImage: "Assets/newbalancebrand/new/d2.png",
        productName: "Newbal",
        productPrice: 197,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/e1.png",
          "Assets/newbalancebrand/new/e2.png",
          "Assets/newbalancebrand/new/e3.png",
          "Assets/newbalancebrand/new/e4.png",
        ],
        productImage: "Assets/newbalancebrand/new/e2.png",
        productName: "Newbal",
        productPrice: 224,
        rating: 3.7),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/f1.png",
          "Assets/newbalancebrand/new/f2.png",
          "Assets/newbalancebrand/new/f3.png",
          "Assets/newbalancebrand/new/f4.png",
        ],
        productImage: "Assets/newbalancebrand/new/f3.png",
        productName: "Newbal",
        productPrice: 233,
        rating: 5.1),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/g1.png",
          "Assets/newbalancebrand/new/g2.png",
          "Assets/newbalancebrand/new/g3.png",
          "Assets/newbalancebrand/new/g4.png",
        ],
        productImage: "Assets/newbalancebrand/new/g2.png",
        productName: "Newbal",
        productPrice: 242,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/h1.png",
          "Assets/newbalancebrand/new/h2.png",
          "Assets/newbalancebrand/new/h3.png",
          "Assets/newbalancebrand/new/h4.png",
        ],
        productImage: "Assets/newbalancebrand/new/h2.png",
        productName: "Newbal",
        productPrice: 251,
        rating: 4.3),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/j1.png",
          "Assets/newbalancebrand/new/j2.png",
          "Assets/newbalancebrand/new/j3.png",
          "Assets/newbalancebrand/new/j4.png",
        ],
        productImage: "Assets/newbalancebrand/new/j2.png",
        productName: "Newbal",
        productPrice: 260,
        rating: 4.0),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/k1.png",
          "Assets/newbalancebrand/new/k2.png",
          "Assets/newbalancebrand/new/k3.png",
          "Assets/newbalancebrand/new/k4.png",
        ],
        productImage: "Assets/newbalancebrand/new/k2.png",
        productName: "Newbal",
        productPrice: 269,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/t1.png",
          "Assets/newbalancebrand/new/t2.png",
          "Assets/newbalancebrand/new/t3.png",
          "Assets/newbalancebrand/new/t4.png",
        ],
        productImage: "Assets/newbalancebrand/new/t2.png",
        productName: "Newbal",
        productPrice: 197,
        rating: 5.7),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/v1.png",
          "Assets/newbalancebrand/new/v2.png",
          "Assets/newbalancebrand/new/v3.png",
          "Assets/newbalancebrand/new/v4.png",
        ],
        productImage: "Assets/newbalancebrand/new/v3.png",
        productName: "Newbal",
        productPrice: 278,
        rating: 4.4),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/z1.png",
          "Assets/newbalancebrand/new/z2.png",
          "Assets/newbalancebrand/new/z3.png",
          "Assets/newbalancebrand/new/z4.png",
        ],
        productImage: "Assets/newbalancebrand/new/z2.png",
        productName: "Newbal",
        productPrice: 287,
        rating: 4.9),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/a5.png",
          "Assets/newbalancebrand/new/a6.png",
          "Assets/newbalancebrand/new/a7.png",
          "Assets/newbalancebrand/new/a8.png",
        ],
        productImage: "Assets/newbalancebrand/new/a6.png",
        productName: "Newbal",
        productPrice: 296,
        rating: 3.9),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/b5.png",
          "Assets/newbalancebrand/new/b6.png",
          "Assets/newbalancebrand/new/b7.png",
          "Assets/newbalancebrand/new/b8.png",
        ],
        productImage: "Assets/newbalancebrand/new/b6.png",
        productName: "Newbal",
        productPrice: 197,
        rating: 5.5),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/c5.png",
          "Assets/newbalancebrand/new/c6.png",
          "Assets/newbalancebrand/new/c7.png",
          "Assets/newbalancebrand/new/c8.png",
        ],
        productImage: "Assets/newbalancebrand/new/c6.png",
        productName: "Newbal",
        productPrice: 305,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/d5.png",
          "Assets/newbalancebrand/new/d6.png",
          "Assets/newbalancebrand/new/d7.png",
          "Assets/newbalancebrand/new/d8.png",
        ],
        productImage: "Assets/newbalancebrand/new/d7.png",
        productName: "Newbal",
        productPrice: 314,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/e5.png",
          "Assets/newbalancebrand/new/e6.png",
          "Assets/newbalancebrand/new/e7.png",
          "Assets/newbalancebrand/new/e8.png",
        ],
        productImage: "Assets/newbalancebrand/new/e6.png",
        productName: "Newbal",
        productPrice: 323,
        rating: 5.4),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/f5.png",
          "Assets/newbalancebrand/new/f6.png",
          "Assets/newbalancebrand/new/f7.png",
          "Assets/newbalancebrand/new/f8.png",
        ],
        productImage: "Assets/newbalancebrand/new/f6.png",
        productName: "Newbal",
        productPrice: 332,
        rating: 5.8),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/g5.png",
          "Assets/newbalancebrand/new/g6.png",
          "Assets/newbalancebrand/new/g7.png",
          "Assets/newbalancebrand/new/g8.png",
        ],
        productImage: "Assets/newbalancebrand/new/g5.png",
        productName: "Newbal",
        productPrice: 197,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/h5.png",
          "Assets/newbalancebrand/new/h6.png",
          "Assets/newbalancebrand/new/h7.png",
          "Assets/newbalancebrand/new/h8.png",
        ],
        productImage: "Assets/newbalancebrand/new/h5.png",
        productName: "Newbal",
        productPrice: 341,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/j5.png",
          "Assets/newbalancebrand/new/j6.png",
          "Assets/newbalancebrand/new/j7.png",
          "Assets/newbalancebrand/new/j8.png",
        ],
        productImage: "Assets/newbalancebrand/new/j6.png",
        productName: "Newbal",
        productPrice: 350,
        rating: 6.0),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/k5.png",
          "Assets/newbalancebrand/new/k6.png",
          "Assets/newbalancebrand/new/k7.png",
          "Assets/newbalancebrand/new/k8.png",
        ],
        productImage: "Assets/newbalancebrand/new/k6.png",
        productName: "Newbal",
        productPrice: 359,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/newbalancebrand/new/t5.png",
          "Assets/newbalancebrand/new/t6.png",
          "Assets/newbalancebrand/new/t7.png",
          "Assets/newbalancebrand/new/t8.png",
        ],
        productImage: "Assets/newbalancebrand/new/t5.png",
        productName: "Newbal",
        productPrice: 368,
        rating: 3.5),
  ];
  static List<DataModel> fila = [
    DataModel(
        subImages: [
          "Assets/filabrand/fill/a1.png",
          "Assets/filabrand/fill/a2.png",
          "Assets/filabrand/fill/a3.png",
          "Assets/filabrand/fill/a4.png",
        ],
        productImage: "Assets/filabrand/fill/a2.png",
        productName: "Fila",
        productPrice: 190,
        rating: 5.7),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/b1.png",
          "Assets/filabrand/fill/b2.png",
          "Assets/filabrand/fill/b3.png",
          "Assets/filabrand/fill/b4.png",
        ],
        productImage: "Assets/filabrand/fill/b2.png",
        productName: "Fila",
        productPrice: 201,
        rating: 3.7),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/c1.png",
          "Assets/filabrand/fill/c2.png",
          "Assets/filabrand/fill/c3.png",
          "Assets/filabrand/fill/c4.png",
        ],
        productImage: "Assets/filabrand/fill/c3.png",
        productName: "Fila",
        productPrice: 212,
        rating: 5.0),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/d1.png",
          "Assets/filabrand/fill/d2.png",
          "Assets/filabrand/fill/d3.png",
          "Assets/filabrand/fill/d4.png",
        ],
        productImage: "Assets/filabrand/fill/d2.png",
        productName: "Fila",
        productPrice: 223,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/e1.png",
          "Assets/filabrand/fill/e2.png",
          "Assets/filabrand/fill/e3.png",
          "Assets/filabrand/fill/e4.png",
        ],
        productImage: "Assets/filabrand/fill/e2.png",
        productName: "Fila",
        productPrice: 234,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/f1.png",
          "Assets/filabrand/fill/f2.png",
          "Assets/filabrand/fill/f3.png",
          "Assets/filabrand/fill/f4.png",
        ],
        productImage: "Assets/filabrand/fill/f2.png",
        productName: "Fila",
        productPrice: 190,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/g1.png",
          "Assets/filabrand/fill/g2.png",
          "Assets/filabrand/fill/g3.png",
          "Assets/filabrand/fill/g4.png",
        ],
        productImage: "Assets/filabrand/fill/g2.png",
        productName: "Fila",
        productPrice: 245,
        rating: 5.3),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/h1.png",
          "Assets/filabrand/fill/h2.png",
          "Assets/filabrand/fill/h3.png",
          "Assets/filabrand/fill/h4.png",
        ],
        productImage: "Assets/filabrand/fill/h2.png",
        productName: "Fila",
        productPrice: 256,
        rating: 4.5),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/j1.png",
          "Assets/filabrand/fill/j2.png",
          "Assets/filabrand/fill/j3.png",
          "Assets/filabrand/fill/j4.png",
        ],
        productImage: "Assets/filabrand/fill/j2.png",
        productName: "Fila",
        productPrice: 267,
        rating: 4.8),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/p1.png",
          "Assets/filabrand/fill/p2.png",
          "Assets/filabrand/fill/p3.png",
          "Assets/filabrand/fill/p4.png",
        ],
        productImage: "Assets/filabrand/fill/p2.png",
        productName: "Fila",
        productPrice: 278,
        rating: 5.2),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/v1.png",
          "Assets/filabrand/fill/v2.png",
          "Assets/filabrand/fill/v3.png",
          "Assets/filabrand/fill/v4.png",
        ],
        productImage: "Assets/filabrand/fill/v2.png",
        productName: "Fila",
        productPrice: 289,
        rating: 4.7),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/z1.png",
          "Assets/filabrand/fill/z2.png",
          "Assets/filabrand/fill/z3.png",
          "Assets/filabrand/fill/z4.png",
        ],
        productImage: "Assets/filabrand/fill/z2.png",
        productName: "Fila",
        productPrice: 300,
        rating: 5.8),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/a5.png",
          "Assets/filabrand/fill/a6.png",
          "Assets/filabrand/fill/a7.png",
          "Assets/filabrand/fill/a8.png",
        ],
        productImage: "Assets/filabrand/fill/a6.png",
        productName: "Fila",
        productPrice: 311,
        rating: 3.9),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/b5.png",
          "Assets/filabrand/fill/b6.png",
          "Assets/filabrand/fill/b7.png",
          "Assets/filabrand/fill/b8.png",
        ],
        productImage: "Assets/filabrand/fill/b6.png",
        productName: "Fila",
        productPrice: 190,
        rating: 3.8),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/c5.png",
          "Assets/filabrand/fill/c6.png",
          "Assets/filabrand/fill/c7.png",
          "Assets/filabrand/fill/c8.png",
        ],
        productImage: "Assets/filabrand/fill/c6.png",
        productName: "Fila",
        productPrice: 322,
        rating: 5.6),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/d5.png",
          "Assets/filabrand/fill/d6.png",
          "Assets/filabrand/fill/d7.png",
          "Assets/filabrand/fill/d8.png",
        ],
        productImage: "Assets/filabrand/fill/d7.png",
        productName: "Fila",
        productPrice: 333,
        rating: 4.6),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/e5.png",
          "Assets/filabrand/fill/e6.png",
          "Assets/filabrand/fill/e7.png",
          "Assets/filabrand/fill/e8.png",
        ],
        productImage: "Assets/filabrand/fill/e6.png",
        productName: "Fila",
        productPrice: 190,
        rating: 6.0),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/f5.png",
          "Assets/filabrand/fill/f6.png",
          "Assets/filabrand/fill/f7.png",
          "Assets/filabrand/fill/f8.png",
        ],
        productImage: "Assets/filabrand/fill/f6.png",
        productName: "Fila",
        productPrice: 344,
        rating: 3.1),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/g5.png",
          "Assets/filabrand/fill/g6.png",
          "Assets/filabrand/fill/g7.png",
          "Assets/filabrand/fill/g8.png",
        ],
        productImage: "Assets/filabrand/fill/g6.png",
        productName: "Fila",
        productPrice: 355,
        rating: 3.5),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/h5.png",
          "Assets/filabrand/fill/h6.png",
          "Assets/filabrand/fill/h7.png",
          "Assets/filabrand/fill/h8.png",
        ],
        productImage: "Assets/filabrand/fill/h6.png",
        productName: "Fila",
        productPrice: 366,
        rating: 4.2),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/j5.png",
          "Assets/filabrand/fill/j6.png",
          "Assets/filabrand/fill/j7.png",
          "Assets/filabrand/fill/j8.png",
        ],
        productImage: "Assets/filabrand/fill/j6.png",
        productName: "Fila",
        productPrice: 377,
        rating: 3.4),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/p5.png",
          "Assets/filabrand/fill/p6.png",
          "Assets/filabrand/fill/p7.png",
          "Assets/filabrand/fill/p8.png",
        ],
        productImage: "Assets/filabrand/fill/p6.png",
        productName: "Fila",
        productPrice: 388,
        rating: 5.9),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/v5.png",
          "Assets/filabrand/fill/v6.png",
          "Assets/filabrand/fill/v7.png",
          "Assets/filabrand/fill/v8.png",
        ],
        productImage: "Assets/filabrand/fill/v6.png",
        productName: "Fila",
        productPrice: 190,
        rating: 4.1),
    DataModel(
        subImages: [
          "Assets/filabrand/fill/z5.png",
          "Assets/filabrand/fill/z6.png",
          "Assets/filabrand/fill/z7.png",
          "Assets/filabrand/fill/z8.png",
        ],
        productImage: "Assets/filabrand/fill/z7.png",
        productName: "Fila",
        productPrice: 270,
        rating: 5.3),
  ];
}
